 ; ASSERT SUCCEEDS: call i64 @test_addition()
 ; ASSERT SUCCEEDS: call i64 @test_overflow()
 ; ASSERT SUCCEEDS: call i64 @test_foo()
 ; ASSERT SUCCEEDS: call i64 @test_xfails()
 ; ASSERT SUCCEEDS: call i64 @test_subtraction()
 ; ASSERT SUCCEEDS: call i64 @test_underflow()
