 ; ASSERT SUCCEEDS: call i64 @test_multiple_three()
 ; ASSERT SUCCEEDS: call i64 @test_multiple_three()
 ; ASSERT SUCCEEDS: call i64 @test_early_returns()
 ; ASSERT SUCCEEDS: call i64 @test_idiomatic_switch()
 ; ASSERT SUCCEEDS: call i64 @test_break_multiple_loops()
 ; ASSERT SUCCEEDS: call i64 @test_irreducible()
 ; ASSERT SUCCEEDS: call i64 @test_stmt_expr_relooper()
 ; ASSERT SUCCEEDS: call i64 @test_nothing()
