 ; ASSERT SUCCEEDS: call i64 @test_unpack_128_2x128()
 ; ASSERT SUCCEEDS: call i64 @test_zero_initializers()
 ; ASSERT SUCCEEDS: call i64 @test_shuffle_vectors()
 ; ASSERT SUCCEEDS: call i64 @test_vector_init_lists()
 ; ASSERT SUCCEEDS: call i64 @test_static_init_lists()
