 ; ASSERT SUCCEEDS: call i64 @test_atomics()
 ; ASSERT SUCCEEDS: call i64 @test_new_atomics()
 ; ASSERT SUCCEEDS: call i64 @test_mem_fns()
 ; ASSERT SUCCEEDS: call i64 @test_ffs()
 ; ASSERT SUCCEEDS: call i64 @test_clang9_intrinsics()
 ; ASSERT SUCCEEDS: call i64 @test_assume_aligned()
