 ; ASSERT SUCCEEDS: call i64 @test_sized_array_impls()
 ; ASSERT SUCCEEDS: call i64 @test_global_incomplete_array()
 ; ASSERT SUCCEEDS: call i64 @test_buffer()
 ; ASSERT SUCCEEDS: call i64 @test_buffer2()
 ; ASSERT SUCCEEDS: call i64 @test_variable_arrays()
 ; ASSERT SUCCEEDS: call i64 @test_alloca_arrays()
