 ; ASSERT SUCCEEDS: call i64 @test_arithmetic_test_buffer()
 ; ASSERT SUCCEEDS: call i64 @test_compound_assignment_test_buffer()
 ; ASSERT SUCCEEDS: call i64 @test_const()
 ; ASSERT SUCCEEDS: call i64 @test_size_t_buffer()
 ; ASSERT SUCCEEDS: call i64 @test_chars_buffer()
 ; ASSERT SUCCEEDS: call i64 @test_sieve_test_buffer()
 ; ASSERT SUCCEEDS: call i64 @test_volatile_test_buffer()
 ; Expected failures below.
 ; NOASSERT SUCCEEDS: call i64 @test_identity()
 ; NOASSERT SUCCEEDS: call i64 @test_implicit_int()
